
LSH - Best configuration:
  Recall@50: 0.0433
  QPS: 3376.60
  Parameters: {'lsh_L': 5, 'lsh_k': 4, 'lsh_w': 2.0}

HYPERCUBE - Best configuration:
  Recall@50: 0.0959
  QPS: 24.11
  Parameters: {'hc_kproj': 10, 'hc_w': 2.0, 'hc_max_probes': 5, 'hc_M': 8000}

IVFFLAT - Best configuration:
  Recall@50: 0.2121
  QPS: 643.87
  Parameters: {'ivf_n_clusters': 1000, 'ivf_n_probe': 100}

IVFPQ - Best configuration:
  Recall@50: 0.2462
  QPS: 1524.14
  Parameters: {'ivf_n_clusters': 2000, 'ivf_n_probe': 30, 'ivf_M': 32, 'ivf_nbits': 8}

NEURAL-LSH - Best configuration:
  Recall@50: N/A
  QPS: N/A
  Parameters: {'nlsh_m': 200, 'nlsh_k': 15, 'nlsh_T': 30, 'nlsh_epochs': 15}